name: Deploy to Botsonic

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Deploy to Botsonic
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.BOTSONIC_API_KEY }}" -F "file=@path/to/your/code.zip" https://api.botsonic.com/deploy
